"""
Sprint 2 — Merge direct n=10^6 measurements with the existing
scalability CSV and regenerate tab_scalability.tex + fig6_scalability.

After running run_scalability_n1e6.py, this script:
  1. Loads analysis/results/scalability_benchmark.csv (existing, n up to 10^5)
  2. Loads analysis/results/scalability_n1e6.csv (new, n=10^6)
  3. Concatenates them
  4. Re-fits the log-log regression using the full size range
  5. Writes a new tab_scalability.tex (without "extrap." columns)
  6. Writes a new fig6_scalability.pdf/.png with measured n=10^6 points

Run from project root:
    python analysis/merge_scalability.py
"""
import os
import sys
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, PROJECT_ROOT)

CSV_OLD = os.path.join(PROJECT_ROOT, "analysis", "results",
                        "scalability_benchmark.csv")
CSV_NEW = os.path.join(PROJECT_ROOT, "analysis", "results",
                        "scalability_n1e6.csv")
CSV_MERGED = os.path.join(PROJECT_ROOT, "analysis", "results",
                           "scalability_merged.csv")
FIG_DIR = os.path.join(PROJECT_ROOT, "paper", "figures")

SIZES_ALL = [1000, 5000, 10000, 50000, 100000, 1000000]
TOPOLOGIES = ["BA", "ER", "WS", "SBM"]


def main():
    print("=" * 72)
    print("  Merge scalability — n=10^5 (existing) + n=10^6 (new)")
    print("=" * 72)

    if not os.path.exists(CSV_OLD):
        print(f"  [FAIL] Existing CSV not found: {CSV_OLD}")
        sys.exit(1)
    if not os.path.exists(CSV_NEW):
        print(f"  [FAIL] New n=10^6 CSV not found: {CSV_NEW}")
        print(f"         Run run_scalability_n1e6.py first.")
        sys.exit(1)

    df_old = pd.read_csv(CSV_OLD)
    df_new = pd.read_csv(CSV_NEW)
    print(f"  Existing rows (n ≤ 10^5): {len(df_old)}")
    print(f"  New rows (n=10^6): {len(df_new)}")

    df = pd.concat([df_old, df_new], ignore_index=True)
    df.to_csv(CSV_MERGED, index=False)
    print(f"  Merged CSV: {CSV_MERGED}")

    # Log-log fit using ALL data (now including n=10^6)
    print("\n  Log-log regression per topology (all measured points):")
    fits = {}
    for topology in TOPOLOGIES:
        sub = df[df["topology"] == topology]
        if len(sub) < 4:
            continue
        agg = sub.groupby("n")["t_total_s"].mean().reset_index()
        log_n = np.log10(agg["n"].values)
        log_t = np.log10(agg["t_total_s"].values)
        slope, intercept = np.polyfit(log_n, log_t, 1)
        # Predict at n=10^6 (will match measured if our fit is good)
        t_at_1e6_pred = 10 ** (slope * 6 + intercept)
        t_at_1e6_meas = agg[agg["n"] == 1_000_000]["t_total_s"].values
        t_at_1e6_meas = float(t_at_1e6_meas[0]) if len(t_at_1e6_meas) else None
        fits[topology] = {
            "exponent": slope, "intercept": intercept,
            "t_at_1e6_pred_s": t_at_1e6_pred,
            "t_at_1e6_meas_s": t_at_1e6_meas,
        }
        meas_str = (f"meas={t_at_1e6_meas:.1f}s" if t_at_1e6_meas else "meas=---")
        print(f"    {topology}: α={slope:.3f}, fit at 10^6={t_at_1e6_pred:.1f}s, "
              f"{meas_str}")

    # Rewrite LaTeX table (no extrapolation column needed)
    write_latex_table(df, fits, os.path.join(FIG_DIR, "tab_scalability.tex"))
    # Rewrite figure
    make_figure(df, fits, os.path.join(FIG_DIR, "fig6_scalability"))
    print(f"\n  Updated tab_scalability.tex and fig6_scalability.pdf/.png")
    print(f"\n  Recompile manuscript to pick up changes:")
    print(f"    cd paper && pdflatex AGEE_manuscript.tex && \\")
    print(f"                bibtex AGEE_manuscript && \\")
    print(f"                pdflatex AGEE_manuscript.tex && \\")
    print(f"                pdflatex AGEE_manuscript.tex")


def write_latex_table(df, fits, out_path):
    """Now with measured n=10^6 column instead of extrapolation."""
    lines = []
    lines.append("% Auto-generated by analysis/merge_scalability.py")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Scalability of AGEE on synthetic large graphs. "
                 "Each cell reports mean wall-clock time (in seconds) for "
                 "the full AGEE pipeline (graph generation + trajectory + "
                 "Leiden partition + $S'I'E'$ compute). All values are "
                 "directly measured on a 32~GB / 16-thread workstation; "
                 "no extrapolation. The empirical scaling exponent "
                 "$\\alpha$ in $t \\propto n^\\alpha$ is obtained by "
                 "log-log regression across all six size points.}")
    lines.append("\\label{tab:scalability}")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\begin{tabular}{lrrrrrrr}")
    lines.append("\\toprule")
    lines.append("\\textbf{Topology} & "
                 "$\\mathbf{10^3}$ & $\\mathbf{5{\\times}10^3}$ & "
                 "$\\mathbf{10^4}$ & $\\mathbf{5{\\times}10^4}$ & "
                 "$\\mathbf{10^5}$ & $\\mathbf{10^6}$ & "
                 "$\\boldsymbol{\\alpha}$ \\\\")
    lines.append("\\midrule")
    for topology in TOPOLOGIES:
        sub = df[df["topology"] == topology]
        if len(sub) == 0:
            continue
        cells = [topology]
        for n in SIZES_ALL:
            data = sub[sub["n"] == n]["t_total_s"]
            if len(data) > 0:
                # Format larger times in minutes
                v = data.mean()
                if v >= 60:
                    cells.append(f"{v:.0f}s ({v/60:.1f}min)")
                else:
                    cells.append(f"{v:.2f}s")
            else:
                cells.append("---")
        if topology in fits:
            cells.append(f"{fits[topology]['exponent']:.2f}")
        else:
            cells.append("---")
        lines.append(" & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def make_figure(df, fits, out_path):
    """Same as run_scalability_benchmark.py's figure but with n=10^6 measured."""
    import matplotlib as mpl
    mpl.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
        "font.size": 9, "axes.labelsize": 10,
        "legend.fontsize": 8, "xtick.labelsize": 8, "ytick.labelsize": 8,
        "pdf.fonttype": 42, "ps.fonttype": 42,
        "axes.spines.top": False, "axes.spines.right": False,
    })

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7.0, 3.0))
    colors = {"BA": "#117733", "ER": "#88CCEE", "WS": "#DDCC77", "SBM": "#CC6677"}
    markers = {"BA": "o", "ER": "s", "WS": "D", "SBM": "^"}

    for topology in TOPOLOGIES:
        sub = df[df["topology"] == topology]
        if len(sub) == 0:
            continue
        agg = sub.groupby("n").agg({"t_total_s": ["mean", "std"],
                                     "mem_delta_gb": "mean"}).reset_index()
        agg.columns = ["n", "t_mean", "t_std", "mem_mean"]
        ax1.errorbar(agg["n"], agg["t_mean"], yerr=agg["t_std"].fillna(0),
                     fmt=markers[topology] + "-", color=colors[topology],
                     label=topology, capsize=2, markersize=5, linewidth=1.0,
                     markeredgecolor="black", markeredgewidth=0.4)
        ax2.plot(agg["n"], agg["mem_mean"], markers[topology] + "-",
                 color=colors[topology], label=topology, markersize=5,
                 linewidth=1.0, markeredgecolor="black", markeredgewidth=0.4)

    ax1.set_xscale("log")
    ax1.set_yscale("log")
    ax1.set_xlabel(r"Graph size $n$")
    ax1.set_ylabel("Wall-clock time (s)")
    ax1.legend(loc="upper left", fontsize=7, frameon=False)
    ax1.grid(True, which="both", alpha=0.2, linestyle="--", linewidth=0.4)

    ax2.set_xscale("log")
    ax2.set_xlabel(r"Graph size $n$")
    ax2.set_ylabel("Peak memory delta (GB)")
    ax2.legend(loc="upper left", fontsize=7, frameon=False)
    ax2.grid(True, which="both", alpha=0.2, linestyle="--", linewidth=0.4)

    plt.tight_layout()
    plt.savefig(out_path + ".pdf", bbox_inches="tight")
    plt.savefig(out_path + ".png", bbox_inches="tight", dpi=200)
    plt.close()


if __name__ == "__main__":
    main()
