"""
Sprint 2 — Merge real Llama/Mistral measurements with synthetic estimates.

After running:
  1. run_kgqa_real_multillm.py --model llama3.1:8b --suffix llama3_1_8b
  2. run_kgqa_real_multillm.py --model mistral:7b-instruct-v0.3 \\
       --suffix mistral_7b_v0_3

This script rebuilds tab_multi_llm.tex with:
  - Qwen-2.5-7B:  measured (Sprint 1)
  - Llama-3.1-8B: MEASURED (new!)
  - Mistral-7B-v0.3: MEASURED (new!)
  - Qwen-2.5-14B: still synthetic
  - GPT-4o-mini:  still synthetic

Source column in the table reflects this mix accurately.

Run from project root:
    python analysis/merge_real_llm.py
"""
import os
import sys
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from scipy.stats import binomtest

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, PROJECT_ROOT)

OUT_DIR = os.path.join(PROJECT_ROOT, "analysis", "results")
FIG_DIR = os.path.join(PROJECT_ROOT, "paper", "figures")

# Paths to the real-LLM CSVs (produced by run_kgqa_real_multillm.py)
REAL_LLM_CSVS = {
    "Llama-3.1-8B":      "kgqa_experiment/results/kgqa_real_llm_llama3_1_8b.csv",
    "Mistral-7B-v0.3":   "kgqa_experiment/results/kgqa_real_llm_mistral_7b_v0_3.csv",
}

# Path to the original synthetic summary (everything else stays)
SYNTH_SUMMARY = os.path.join(OUT_DIR, "multi_llm_synthetic_summary.csv")

# Path to Sprint 1 main CSV (for Qwen-7B measured values, in case we want
# to verify they match the synthetic table's "measured" row)
SPRINT1_CSV = os.path.join(PROJECT_ROOT, "kgqa_experiment", "results",
                            "kgqa_trajectories.csv")


def boot_ci(x, n_boot=1000, rng=None, alpha=0.05):
    """Bootstrap percentile CI on the mean of x."""
    if rng is None:
        rng = np.random.default_rng(42)
    a = np.asarray(x, dtype=float)
    a = a[~np.isnan(a)]
    if len(a) < 2:
        return np.nan, np.nan
    boots = np.array([rng.choice(a, size=len(a), replace=True).mean()
                      for _ in range(n_boot)])
    return np.percentile(boots, 100 * alpha / 2), \
           np.percentile(boots, 100 * (1 - alpha / 2))


def summarise_real_csv(llm_name, csv_path, rng):
    """Compute the same summary stats as multi_llm_synthetic_summary.csv."""
    if not os.path.exists(csv_path):
        print(f"  [SKIP] {llm_name}: CSV not found at {csv_path}")
        return None

    df = pd.read_csv(csv_path)
    if "skip_reason" not in df.columns:
        df["skip_reason"] = ""
    df["skip_reason"] = df["skip_reason"].fillna("")

    n_total = len(df)
    if n_total == 0:
        print(f"  [SKIP] {llm_name}: empty CSV")
        return None

    # Classify memory vs traversal mode
    df["mode"] = df["traj_length"].apply(
        lambda t: "memory" if t <= 1 else "traversal"
    )
    memory_df = df[df["mode"] == "memory"]
    traversal_df = df[(df["mode"] == "traversal") &
                       (df["skip_reason"] == "")]

    # Hits@1 overall (Clopper-Pearson)
    n_hits = int(df["hit"].sum())
    hit_ci = binomtest(n_hits, n_total).proportion_ci(0.95)

    # Memory rate (Clopper-Pearson)
    n_memory = len(memory_df)
    memory_ci = binomtest(n_memory, n_total).proportion_ci(0.95)

    # Continuous metrics on traversal-mode trajectories
    if len(traversal_df) > 0:
        agee_lo, agee_hi = boot_ci(traversal_df["agee"].values, rng=rng)
        S_lo, S_hi = boot_ci(traversal_df["coverage"].values, rng=rng)
        I_lo, I_hi = boot_ci(traversal_df["info_rate"].values, rng=rng)
        E_lo, E_hi = boot_ci(traversal_df["efficiency"].values, rng=rng)
        agee_mean = traversal_df["agee"].mean()
        S_mean = traversal_df["coverage"].mean()
        I_mean = traversal_df["info_rate"].mean()
        E_mean = traversal_df["efficiency"].mean()
    else:
        agee_mean = S_mean = I_mean = E_mean = np.nan
        agee_lo = agee_hi = S_lo = S_hi = I_lo = I_hi = E_lo = E_hi = np.nan

    return {
        "llm": llm_name,
        "source": "measured",
        "n": n_total,
        "memory_rate": n_memory / n_total,
        "memory_rate_lo": memory_ci.low,
        "memory_rate_hi": memory_ci.high,
        "hits_overall": n_hits / n_total,
        "hits_overall_lo": hit_ci.low,
        "hits_overall_hi": hit_ci.high,
        "agee_traversal": agee_mean,
        "agee_lo": agee_lo, "agee_hi": agee_hi,
        "S_traversal": S_mean, "S_lo": S_lo, "S_hi": S_hi,
        "I_traversal": I_mean, "I_lo": I_lo, "I_hi": I_hi,
        "E_traversal": E_mean, "E_lo": E_lo, "E_hi": E_hi,
    }


def write_latex_table(summary, out_path):
    """Identical formatting to run_multi_llm_synthetic.py's writer."""
    lines = []
    lines.append("% Auto-generated by analysis/merge_real_llm.py")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Multi-LLM scaling on MetaQA-2hop. Qwen-2.5-7B, "
                 "Llama-3.1-8B, and Mistral-7B-v0.3 are measured "
                 "($N=200$ each, real Ollama runs); Qwen-2.5-14B and "
                 "GPT-4o-mini remain synthetic estimates based on "
                 "published behavioural parameters (real runs deferred "
                 "to camera-ready revision). Memory rate is the fraction "
                 "of attempts where the agent produces an "
                 "\\texttt{ANSWER:} declaration without graph traversal. "
                 "AGEE, $S'$, $I'$, $E'$ are reported on traversal-mode "
                 "trajectories only. 95\\% CIs are Clopper-Pearson "
                 "(proportions) and bootstrap (continuous).}")
    lines.append("\\label{tab:multillm}")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("\\begin{tabular}{llccccc}")
    lines.append("\\toprule")
    lines.append("\\textbf{LLM} & \\textbf{Source} & "
                 "\\textbf{Mem rate} & \\textbf{Hits@1} & "
                 "\\textbf{AGEE} & \\textbf{$S'$} & \\textbf{$I'$} \\\\")
    lines.append("\\midrule")
    for r in summary:
        src = r["source"]
        mem = (f"{r['memory_rate']:.2f} {{\\scriptsize "
               f"[{r['memory_rate_lo']:.2f},{r['memory_rate_hi']:.2f}]}}")
        hit = (f"{r['hits_overall']:.2f} {{\\scriptsize "
               f"[{r['hits_overall_lo']:.2f},{r['hits_overall_hi']:.2f}]}}")
        agee = (f"{r['agee_traversal']:.2f} {{\\scriptsize "
                f"[{r['agee_lo']:.2f},{r['agee_hi']:.2f}]}}")
        S = (f"{r['S_traversal']:.2f} {{\\scriptsize "
             f"[{r['S_lo']:.2f},{r['S_hi']:.2f}]}}")
        I = (f"{r['I_traversal']:.2f} {{\\scriptsize "
             f"[{r['I_lo']:.2f},{r['I_hi']:.2f}]}}")
        lines.append(f"{r['llm']} & {src} & {mem} & {hit} & {agee} & "
                     f"{S} & {I} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    print("=" * 72)
    print("  Merge real-LLM measurements with synthetic estimates")
    print("=" * 72)

    rng = np.random.default_rng(42)

    # Start from the synthetic summary
    if not os.path.exists(SYNTH_SUMMARY):
        print(f"  [FAIL] Synthetic summary not found: {SYNTH_SUMMARY}")
        sys.exit(1)
    synth_df = pd.read_csv(SYNTH_SUMMARY)
    print(f"  Loaded synthetic summary: {len(synth_df)} rows")

    # Build replacement rows from real-LLM CSVs
    replacements = {}
    for llm_name, rel_path in REAL_LLM_CSVS.items():
        full_path = os.path.join(PROJECT_ROOT, rel_path)
        result = summarise_real_csv(llm_name, full_path, rng)
        if result is not None:
            replacements[llm_name] = result
            print(f"  [OK] {llm_name}: N={result['n']}, "
                  f"mem_rate={result['memory_rate']:.3f}, "
                  f"hits={result['hits_overall']:.3f}, "
                  f"agee_trav={result['agee_traversal']:.3f}")

    # Merge: replace synthetic rows with real ones where available
    summary = []
    # Order: Qwen-7B, Llama, Mistral, Qwen-14B, GPT-4o-mini
    order = ["Qwen-2.5-7B", "Llama-3.1-8B", "Mistral-7B-v0.3",
             "Qwen-2.5-14B", "GPT-4o-mini"]
    for llm in order:
        if llm in replacements:
            summary.append(replacements[llm])
        else:
            row = synth_df[synth_df["llm"] == llm]
            if len(row) == 0:
                print(f"  [WARN] {llm} not in synth_summary, skipping")
                continue
            summary.append(row.iloc[0].to_dict())

    print(f"\n  Final summary: {len(summary)} rows")
    for r in summary:
        print(f"    {r['llm']:<18} src={r['source']:<10} "
              f"mem={r['memory_rate']:.2f}  hits={r['hits_overall']:.2f}  "
              f"agee={r['agee_traversal']:.2f}")

    # Save merged CSV
    merged_csv = os.path.join(OUT_DIR, "multi_llm_merged_summary.csv")
    pd.DataFrame(summary).to_csv(merged_csv, index=False)
    print(f"\n  Merged CSV: {merged_csv}")

    # Rewrite the LaTeX table
    tab_path = os.path.join(FIG_DIR, "tab_multi_llm.tex")
    write_latex_table(summary, tab_path)
    print(f"  LaTeX table: {tab_path}")
    print("\n  Now recompile the manuscript to pick up new values:")
    print("    cd paper && pdflatex AGEE_manuscript.tex && \\")
    print("                bibtex AGEE_manuscript && \\")
    print("                pdflatex AGEE_manuscript.tex && \\")
    print("                pdflatex AGEE_manuscript.tex")


if __name__ == "__main__":
    main()
